linkdingNetwork:
  webPort: 31000

linkdingRunAs:
  user: 1000
  group: 1000

linkdingConfig:
  username: admin
  password: admin

linkdingStorage:
  data:
    type: hostPath
    hostPath: /mnt/{{ .Release.Namespace }}/data
  pgData:
    type: hostPath
    hostPath: /mnt/{{ .Release.Namespace }}/pgData
  pgBackup:
    type: hostPath
    hostPath: /mnt/{{ .Release.Namespace }}/pgBackup
