image:
  repository: registry.departy.xyz/frigate2discord
  pullPolicy: IfNotPresent
  tag: '2024.02.01'


resources:
  limits:
    cpu: 4000m
    memory: 1Gi

frigate2discordConfig:
  instanceName: frigate2discord
  additionalEnvs: []
frigate2discordNetwork:
  webPort: 30027
  hostNetwork: false
frigate2discordRunAs:
  user: 568
  group: 568
frigate2discordStorage:
  config:
    type: ixVolume
    datasetName: config
  additionalStorages: []
