image:
  repository: registry.departy.xyz/frigate2discord
  pullPolicy: IfNotPresent
  tag: '2024.02.01'


resources:
  limits:
    cpu: 4000m
    memory: 1Gi

frigate2discordConfig:
  instanceName: frigate2discord
  additionalEnvs: []
frigate2discordNetwork:
  webPort: "{{ .Values.network.webPort }}"
  hostNetwork: false
frigate2discordRunAs:
  user: "{{ .Values.runas.user }}"
  group: "{{ .Values.runas.group }}"
frigate2discordStorage:
  config:
    type: ixVolume
    datasetName: config
  additionalStorages: []
